'use client';
import{useState,useEffect,useCallback}from'react';import Sidebar from'@/components/Sidebar';
import{LineChart,Line,BarChart,Bar,PieChart,Pie,Cell,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer}from'recharts';
const fmt=(v)=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const fmtK=(v)=>Math.abs(v)>=100000?`₹${(v/100000).toFixed(1)}L`:Math.abs(v)>=1000?`₹${(v/1000).toFixed(1)}K`:fmt(v);
const pct=(v)=>`${Number(v||0).toFixed(1)}%`;
const COLORS=['#f97316','#3b82f6','#10b981','#8b5cf6','#ef4444','#06b6d4'];
const fmtMonth=(m)=>{if(!m||m==='alltime')return'All Time';const[y,mo]=m.split('-');return new Date(parseInt(y),parseInt(mo)-1).toLocaleString('en-IN',{month:'short',year:'numeric'});};
function StatCard({label,value,sub,color='orange',icon}){const bg={orange:'bg-orange-50 text-orange-600',green:'bg-green-50 text-green-600',blue:'bg-blue-50 text-blue-600',red:'bg-red-50 text-red-600',purple:'bg-purple-50 text-purple-600',gray:'bg-gray-100 text-gray-500'};return(<div className="card p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">{label}</p><p className="text-2xl font-bold text-gray-900">{value}</p>{sub&&<p className="text-xs text-gray-500 mt-1">{sub}</p>}</div><div className={`w-10 h-10 rounded-xl flex items-center justify-center text-xl ${bg[color]}`}>{icon}</div></div></div>);}
export default function DashboardPage(){
  const[months,setMonths]=useState([]);const[selectedMonth,setSelected]=useState('');const[data,setData]=useState(null);const[allTimeData,setAllTimeData]=useState(null);const[loading,setLoading]=useState(false);const isAllTime=selectedMonth==='alltime';
  useEffect(()=>{fetch('/api/months',{cache:'no-store'}).then(r=>r.json()).then(ms=>{setMonths(ms);if(ms.length>0)setSelected(ms[0].month);});},[]);
  const loadAnalytics=useCallback(()=>{if(!selectedMonth)return;setLoading(true);setData(null);setAllTimeData(null);if(selectedMonth==='alltime'){fetch('/api/alltime').then(r=>r.json()).then(d=>{setAllTimeData(d);setLoading(false);}).catch(()=>setLoading(false));}else{fetch(`/api/analytics?month=${selectedMonth}`).then(r=>r.json()).then(d=>{setData(d);setLoading(false);}).catch(()=>setLoading(false));}},[selectedMonth]);
  useEffect(()=>{loadAnalytics();},[loadAnalytics]);
  const s=data?.summary;
  const chargesBreakdown=s?[{name:'Commission+GST',value:Math.abs(s.commission)},{name:'Shipping+GST',value:Math.abs(s.shipping)},{name:'Storage',value:Math.abs(s.storage)},{name:'TDS/TCS',value:Math.abs(s.tds_tcs)},{name:'Return Fee',value:Math.abs(s.return_charge)},{name:'Ads',value:Math.abs(s.ads_spend)}].filter(c=>c.value>0):[];
  const byUnits=data?.products?[...data.products].sort((a,b)=>b.units_sold-a.units_sold).slice(0,8):[];
  const byProfit=data?.products?[...data.products].sort((a,b)=>b.net_profit-a.net_profit).slice(0,8):[];
  const tableProducts=data?.products?[...data.products].sort((a,b)=>b.units_sold-a.units_sold):[];
  const missingCogs=data?.products?.filter(p=>!p.cogs||p.cogs===0).length||0;
  const at=allTimeData?.summary;
  return(<div className="flex min-h-screen"><Sidebar/><main className="flex-1 p-6 overflow-auto">
    <div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold text-gray-900">Dashboard</h1><p className="text-sm text-gray-500">Blinkit Sales Analytics</p></div>
      <select value={selectedMonth} onChange={e=>setSelected(e.target.value)} className="input text-sm font-medium">{months.length===0&&<option value="">No data yet</option>}{months.length>0&&<option value="alltime">📊 All Time</option>}{months.map(m=><option key={m.month} value={m.month}>{fmtMonth(m.month)}</option>)}</select></div>
    {months.length===0?(<div className="card p-12 text-center"><p className="text-4xl mb-4">📤</p><h2 className="text-xl font-semibold text-gray-700 mb-2">No Data Yet</h2><a href="/upload" className="btn-primary inline-block">Upload Files</a></div>
    ):loading?(<div className="flex items-center justify-center h-64"><div className="w-10 h-10 border-4 border-orange-500 border-t-transparent rounded-full animate-spin"></div></div>
    ):isAllTime&&at?(<>
      <div className="bg-purple-50 border border-purple-200 rounded-xl px-4 py-2 mb-4 text-xs text-purple-700">📊 All-time across <strong>{at.months_count}</strong> months</div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
        <StatCard label="Gross Revenue" value={fmt(at.gross_revenue)} sub={`${at.units_net?.toLocaleString('en-IN')} net units`} icon="💰" color="orange"/>
        <StatCard label="Ex-GST Revenue" value={fmt(at.ex_gst_revenue)} sub="after output GST removed" icon="📋" color="blue"/>
        <StatCard label="Blinkit Charges" value={fmt(at.total_blinkit)} sub="all fees" icon="🧾" color="purple"/>
        <StatCard label="Net Profit" value={fmt(at.net_profit)} sub={`${pct(at.margin_pct)} margin`} icon="📈" color={at.net_profit>=0?'green':'red'}/>
      </div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
        <StatCard label="COGS" value={fmt(at.cogs_total)} sub="product cost" icon="🏭" color="orange"/>
        <StatCard label="Ads Spend" value={fmt(at.ads_spend)} sub="all campaigns" icon="📢" color="orange"/>
        <StatCard label="Net Payout" value={fmt(at.net_payout)} sub="from Blinkit" icon="🏦" color="gray"/>
        <StatCard label="Returns" value={at.units_returned} sub={`of ${at.units_sold||0} orders`} icon="↩️" color="gray"/>
      </div>
      {at.best_month&&(<div className="grid grid-cols-2 gap-4 mb-4">
        <div className="card p-4 flex items-center gap-4"><div className="text-3xl">🏆</div><div><p className="text-xs text-gray-500 uppercase">Best Month</p><p className="font-bold text-green-700 text-lg">{fmtMonth(at.best_month.month)}</p><p className="text-sm text-gray-600">Net profit: <strong>{fmt(at.best_month.net_profit)}</strong></p></div></div>
        {at.worst_month&&<div className="card p-4 flex items-center gap-4"><div className="text-3xl">📉</div><div><p className="text-xs text-gray-500 uppercase">Lowest Month</p><p className="font-bold text-red-700 text-lg">{fmtMonth(at.worst_month.month)}</p><p className="text-sm text-gray-600">Net profit: <strong>{fmt(at.worst_month.net_profit)}</strong></p></div></div>}
      </div>)}
      <div className="card p-5 mb-4"><h2 className="font-semibold text-gray-800 mb-4">Revenue & Profit by Month</h2>
        <ResponsiveContainer width="100%" height={240}><BarChart data={allTimeData.byMonth}><CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6"/><XAxis dataKey="month" tickFormatter={fmtMonth} tick={{fontSize:11}}/><YAxis tickFormatter={fmtK} tick={{fontSize:11}}/><Tooltip formatter={v=>fmt(v)} labelFormatter={fmtMonth}/><Legend/><Bar dataKey="ex_gst_revenue" name="Ex-GST Revenue" fill="#f97316" radius={[3,3,0,0]}/><Bar dataKey="net_profit" name="Net Profit" fill="#10b981" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div>
      <div className="card p-5"><h2 className="font-semibold text-gray-800 mb-4">All-Time Product P&L</h2><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="font-medium text-gray-500 uppercase tracking-wider border-b border-gray-100"><th className="text-left pb-3 pr-3">Product</th><th className="text-right pb-3 px-2">Net Units</th><th className="text-right pb-3 px-2">Ex-GST Revenue</th><th className="text-right pb-3 px-2">COGS</th><th className="text-right pb-3 px-2">Net Profit</th><th className="text-right pb-3 pl-2">Margin</th></tr></thead><tbody className="divide-y divide-gray-50">{allTimeData.topProducts.map(p=>(<tr key={p.item_id} className="hover:bg-gray-50"><td className="py-3 pr-3 max-w-[180px]"><p className="font-medium text-gray-800 truncate">{p.product_name}</p></td><td className="py-3 px-2 text-right">{p.units_net}</td><td className="py-3 px-2 text-right">{fmt(p.ex_gst_revenue)}</td><td className="py-3 px-2 text-right text-gray-600">{p.cogs_total>0?fmt(p.cogs_total):<span className="text-amber-500">No COGS</span>}</td><td className={`py-3 px-2 text-right font-semibold ${p.net_profit>=0?'text-green-600':'text-red-600'}`}>{fmt(p.net_profit)}</td><td className={`py-3 pl-2 text-right font-medium ${p.margin_pct>=20?'text-green-600':p.margin_pct>=0?'text-amber-600':'text-red-600'}`}>{pct(p.margin_pct)}</td></tr>))}</tbody></table></div></div>
    </>):s?(<>
      {missingCogs>0&&(<div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 mb-4 text-sm text-amber-800 flex items-center justify-between"><span>⚠️ <strong>{missingCogs} product{missingCogs>1?'s':''}</strong> missing COGS</span><a href="/products" className="underline font-medium">Set COGS →</a></div>)}
      <div className="bg-gray-50 border border-gray-200 rounded-xl px-4 py-2 mb-4 text-xs text-gray-500">💡 <strong>Net Profit = Ex-GST Revenue − Blinkit Charges − COGS</strong> &nbsp;·&nbsp; Output GST ({fmt(s.output_gst)}) removed from revenue &nbsp;·&nbsp; Ads ({fmt(s.ads_spend)}) at account level</div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
        <StatCard label="Gross Revenue" value={fmt(s.gross_revenue)} sub={`${s.units_sold} orders, ${s.units_net} net`} icon="💰" color="orange"/>
        <StatCard label="Ex-GST Revenue" value={fmt(s.ex_gst_revenue)} sub="your actual revenue" icon="📋" color="blue"/>
        <StatCard label="Blinkit Charges" value={fmt(s.total_blinkit)} sub="all fees combined" icon="🧾" color="purple"/>
        <StatCard label="Net Profit" value={fmt(s.net_profit)} sub={`${pct(s.margin_pct)} on ex-GST rev`} icon="📈" color={s.net_profit>=0?'green':'red'}/>
      </div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
        <StatCard label="COGS" value={fmt(s.cogs_total)} sub="product cost" icon="🏭" color="orange"/>
        <StatCard label="Ads Spend" value={fmt(s.ads_spend)} sub="account-level" icon="📢" color="orange"/>
        <StatCard label="Net Payout" value={fmt(s.net_payout)} sub="from Blinkit" icon="🏦" color="gray"/>
        <StatCard label="Return Rate" value={pct(s.return_rate)} sub={`${s.units_returned} returns`} icon="↩️" color={s.return_rate>10?'red':'green'}/>
      </div>
      <div className="grid grid-cols-4 gap-3 mb-4">{[{label:'Commission+GST',v:s.commission},{label:'Shipping+GST',v:s.shipping},{label:'Storage',v:s.storage},{label:'Return Fee+TDS',v:Math.abs(s.return_charge)+Math.abs(s.tds_tcs)}].map(c=>(<div key={c.label} className="card p-4"><p className="text-xs text-gray-500 mb-1">{c.label}</p><p className="text-lg font-bold text-red-600">{fmt(c.v)}</p></div>))}</div>
      <div className="grid grid-cols-3 gap-4 mb-4">
        <div className="card p-5 col-span-2"><h2 className="font-semibold text-gray-800 mb-4">Revenue & Profit Trend</h2>
          <ResponsiveContainer width="100%" height={220}><LineChart data={data.trend}><CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6"/><XAxis dataKey="month" tickFormatter={fmtMonth} tick={{fontSize:11}}/><YAxis tickFormatter={fmtK} tick={{fontSize:11}}/><Tooltip formatter={v=>fmt(v)} labelFormatter={fmtMonth}/><Legend/><Line type="monotone" dataKey="ex_gst_revenue" name="Ex-GST Revenue" stroke="#f97316" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="net_profit" name="Net Profit" stroke="#10b981" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div>
        <div className="card p-5"><h2 className="font-semibold text-gray-800 mb-3">Charges Breakdown</h2>
          <ResponsiveContainer width="100%" height={175}><PieChart><Pie data={chargesBreakdown} cx="50%" cy="50%" innerRadius={45} outerRadius={70} dataKey="value">{chargesBreakdown.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip formatter={v=>fmt(v)}/></PieChart></ResponsiveContainer>
          <div className="space-y-1 mt-1">{chargesBreakdown.map((c,i)=>(<div key={c.name} className="flex items-center justify-between text-xs"><div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full inline-block" style={{background:COLORS[i]}}></span><span className="text-gray-600">{c.name}</span></div><span className="font-medium">{fmt(c.value)}</span></div>))}</div></div>
      </div>
      <div className="grid grid-cols-2 gap-4 mb-4">
        <div className="card p-5"><h2 className="font-semibold text-gray-800 mb-4">Top Products by Units Sold</h2>
          <ResponsiveContainer width="100%" height={220}><BarChart data={byUnits} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6"/><XAxis type="number" tick={{fontSize:10}}/><YAxis type="category" dataKey="product_name" width={130} tick={{fontSize:9}} tickFormatter={v=>v.length>20?v.slice(0,20)+'…':v}/><Tooltip formatter={v=>`${v} units`}/><Bar dataKey="units_net" name="Net Units Sold" fill="#f97316" radius={[0,3,3,0]}/></BarChart></ResponsiveContainer></div>
        <div className="card p-5"><h2 className="font-semibold text-gray-800 mb-4">Top Products by Profit</h2>
          <ResponsiveContainer width="100%" height={220}><BarChart data={byProfit} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6"/><XAxis type="number" tickFormatter={fmtK} tick={{fontSize:10}}/><YAxis type="category" dataKey="product_name" width={130} tick={{fontSize:9}} tickFormatter={v=>v.length>20?v.slice(0,20)+'…':v}/><Tooltip formatter={v=>fmt(v)}/><Bar dataKey="net_profit" name="Net Profit" fill="#10b981" radius={[0,3,3,0]}/></BarChart></ResponsiveContainer></div>
      </div>
      <div className="card p-5 mb-4"><h2 className="font-semibold text-gray-800 mb-1">Product P&L — sorted by units sold ↓</h2>
        <p className="text-xs text-gray-400 mb-4">Net Profit = Ex-GST Revenue − Commission − Shipping − Storage − Return Fee − TDS/TCS − COGS</p>
        <div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="font-medium text-gray-500 uppercase tracking-wider border-b border-gray-100"><th className="text-left pb-3 pr-3">Product</th><th className="text-right pb-3 px-2">Net Units ▼</th><th className="text-right pb-3 px-2">Ex-GST Rev</th><th className="text-right pb-3 px-2">Commission</th><th className="text-right pb-3 px-2">Shipping</th><th className="text-right pb-3 px-2">Storage</th><th className="text-right pb-3 px-2">Ret+Tax</th><th className="text-right pb-3 px-2">COGS</th><th className="text-right pb-3 px-2">Net Profit</th><th className="text-right pb-3 pl-2">Margin</th><th className="text-right pb-3 pl-2">Ret%</th></tr></thead>
        <tbody className="divide-y divide-gray-50">{tableProducts.map(p=>(<tr key={p.item_id} className="hover:bg-gray-50"><td className="py-3 pr-3 max-w-[160px]"><p className="font-medium text-gray-800 truncate">{p.product_name}</p><p className="text-gray-400 font-mono">{p.item_id}</p></td><td className="py-3 px-2 text-right font-medium">{p.units_net}{p.units_returned>0&&<span className="text-gray-400 text-xs ml-1">({p.units_sold}−{p.units_returned})</span>}</td><td className="py-3 px-2 text-right font-medium">{fmt(p.ex_gst_revenue)}</td><td className="py-3 px-2 text-right text-red-500">{fmt(Math.abs(p.commission)+Math.abs(p.commission_gst))}</td><td className="py-3 px-2 text-right text-red-500">{fmt(Math.abs(p.shipping)+Math.abs(p.shipping_gst))}</td><td className="py-3 px-2 text-right text-red-500">{fmt(Math.abs(p.storage_aging)+Math.abs(p.storage_upfront))}</td><td className="py-3 px-2 text-right text-red-500">{fmt(Math.abs(p.return_charge)+Math.abs(p.tds)+Math.abs(p.tcs))}</td><td className="py-3 px-2 text-right text-gray-600">{p.cogs>0?fmt(p.cogs_total):<span className="text-amber-500">Set COGS</span>}</td><td className={`py-3 px-2 text-right font-semibold ${p.net_profit>=0?'text-green-600':'text-red-600'}`}>{fmt(p.net_profit)}</td><td className={`py-3 pl-2 text-right font-medium ${p.margin_pct>=20?'text-green-600':p.margin_pct>=0?'text-amber-600':'text-red-600'}`}>{pct(p.margin_pct)}</td><td className={`py-3 pl-2 text-right ${p.return_rate_pct>10?'text-red-500':'text-gray-500'}`}>{pct(p.return_rate_pct)}</td></tr>))}</tbody>
        <tfoot className="border-t-2 border-gray-200 bg-gray-50 text-sm font-semibold"><tr><td className="py-3 pr-3 text-gray-800">Total</td><td className="py-3 px-2 text-right">{s.units_net}<span className="text-xs font-normal text-gray-400 ml-1">({s.units_sold}−{s.units_returned})</span></td><td className="py-3 px-2 text-right">{fmt(s.ex_gst_revenue)}</td><td className="py-3 px-2 text-right text-red-600">{fmt(s.commission)}</td><td className="py-3 px-2 text-right text-red-600">{fmt(s.shipping)}</td><td className="py-3 px-2 text-right text-red-600">{fmt(s.storage)}</td><td className="py-3 px-2 text-right text-red-600">{fmt(Math.abs(s.return_charge)+Math.abs(s.tds_tcs))}</td><td className="py-3 px-2 text-right text-gray-700">{fmt(s.cogs_total)}</td><td className={`py-3 px-2 text-right ${s.net_profit_pre_ads>=0?'text-green-600':'text-red-600'}`}>{fmt(s.net_profit_pre_ads)}<span className="block text-xs font-normal text-gray-400">−{fmt(s.ads_spend)} ads</span><span className={`block text-xs font-bold ${s.net_profit>=0?'text-green-700':'text-red-700'}`}>= {fmt(s.net_profit)}</span></td><td className={`py-3 pl-2 text-right ${s.margin_pct>=0?'text-green-600':'text-red-600'}`}>{pct(s.margin_pct)}</td><td className="py-3 pl-2 text-right">{pct(s.return_rate)}</td></tr></tfoot></table></div></div>
      {data.adsCampaigns?.length>0&&(<div className="card p-5"><h2 className="font-semibold text-gray-800 mb-4">📢 Ads Performance</h2><table className="w-full text-sm"><thead><tr className="text-xs font-medium text-gray-500 uppercase border-b border-gray-100"><th className="text-left pb-3 pr-4">Campaign</th><th className="text-right pb-3 px-3">Spend</th><th className="text-right pb-3 px-3">Direct Sales</th><th className="text-right pb-3 px-3">Indirect</th><th className="text-right pb-3 px-3">Units</th><th className="text-right pb-3 pl-3">ROAS</th></tr></thead><tbody className="divide-y divide-gray-50">{data.adsCampaigns.map(c=>(<tr key={c.campaign_name} className="hover:bg-gray-50"><td className="py-3 pr-4 font-medium">{c.campaign_name}</td><td className="py-3 px-3 text-right text-red-600">{fmt(c.total_spend)}</td><td className="py-3 px-3 text-right text-green-600">{fmt(c.direct_sales)}</td><td className="py-3 px-3 text-right text-gray-600">{fmt(c.indirect_sales)}</td><td className="py-3 px-3 text-right">{c.qty_sold}</td><td className={`py-3 pl-3 text-right font-semibold ${c.total_roas>=3?'text-green-600':c.total_roas>=1?'text-amber-600':'text-red-600'}`}>{Number(c.total_roas).toFixed(2)}x</td></tr>))}</tbody></table></div>)}
    </>):null}
  </main></div>);}
