'use client';
import{useState,useEffect}from'react';import Sidebar from'@/components/Sidebar';
const fmt=(v)=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const fmtMonth=(m)=>{if(!m)return'';const[y,mo]=m.split('-');return new Date(parseInt(y),parseInt(mo)-1).toLocaleString('en-IN',{month:'short',year:'numeric'});};
export default function InventoryPage(){
  const now=new Date();const defaultMonth=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
  const[viewMonth,setViewMonth]=useState(defaultMonth);const[uploadMonth,setUploadMonth]=useState(defaultMonth);const[data,setData]=useState(null);const[loading,setLoading]=useState(false);const[uploading,setUploading]=useState(false);const[uploadResult,setUploadResult]=useState(null);const[files,setFiles]=useState([null,null,null]);const[uploadMode,setUploadMode]=useState('merge');
  useEffect(()=>{if(!viewMonth)return;setLoading(true);setData(null);fetch(`/api/inventory?month=${viewMonth}`,{cache:'no-store'}).then(r=>r.json()).then(d=>{setData(d);setLoading(false);}).catch(()=>setLoading(false));},[viewMonth]);
  async function handleUpload(e){e.preventDefault();const validFiles=files.filter(Boolean);if(validFiles.length===0){alert('Please select at least one aging CSV file.');return;}setUploading(true);setUploadResult(null);const fd=new FormData();fd.append('month',uploadMonth);fd.append('mode',uploadMode);validFiles.forEach((f,i)=>fd.append(`inv_${i}`,f));try{const res=await fetch('/api/inventory',{method:'POST',body:fd});const d=await res.json();setUploadResult(d);if(res.ok){if(uploadMonth===viewMonth)fetch(`/api/inventory?month=${viewMonth}`,{cache:'no-store'}).then(r=>r.json()).then(dd=>setData(dd));setFiles([null,null,null]);}}catch(err){setUploadResult({error:err.message});}finally{setUploading(false);}}
  const s=data?.summary;const hasData=s&&data.products?.length>0;
  return(<div className="flex min-h-screen"><Sidebar/><main className="flex-1 p-6 overflow-auto">
    <div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold text-gray-900">Inventory & Holding Costs</h1><p className="text-sm text-gray-500">Upload aging CSVs (up to 3 per 31-day month) to track holding costs by age slab.</p></div><div className="flex items-center gap-2"><span className="text-sm text-gray-500">Viewing:</span><input type="month" value={viewMonth} onChange={e=>setViewMonth(e.target.value)} className="input text-sm font-medium"/></div></div>
    <div className="card p-5 mb-6"><h2 className="font-semibold text-gray-800 mb-1">Upload Aging CSVs</h2><p className="text-xs text-gray-500 mb-4">Export <strong>seller_data.csv</strong> from Blinkit Seller → Reports → Inventory Aging. A 31-day month gives ~3 files. Use <strong>Merge</strong> to combine.</p>
      <form onSubmit={handleUpload} className="space-y-4"><div className="grid grid-cols-3 gap-3">{[0,1,2].map(i=>(<label key={i} className={`block border-2 border-dashed rounded-xl p-3 cursor-pointer transition-colors ${files[i]?'border-green-400 bg-green-50':'border-gray-200 hover:border-orange-300'}`}><input type="file" accept=".csv,.xlsx,.xls" className="sr-only" onChange={e=>{const nf=[...files];nf[i]=e.target.files[0]||null;setFiles(nf);}}/><p className="text-xs font-medium text-gray-700 truncate">{files[i]?`✅ ${files[i].name}`:`📄 File ${i+1} (optional)`}</p><p className="text-xs text-gray-400 mt-0.5">seller_data.csv</p></label>))}</div>
        <div className="flex items-center gap-4 flex-wrap"><div className="flex items-center gap-3">{[['merge','🔀 Merge'],['replace','🔄 Replace']].map(([v,l])=>(<label key={v} className="flex items-center gap-1.5 cursor-pointer text-sm"><input type="radio" name="invMode" value={v} checked={uploadMode===v} onChange={()=>setUploadMode(v)}/>{l}</label>))}</div><div className="flex items-center gap-2 ml-auto"><span className="text-sm text-gray-500">For month:</span><input type="month" value={uploadMonth} onChange={e=>setUploadMonth(e.target.value)} className="input text-sm"/></div><button type="submit" disabled={uploading} className="btn-primary disabled:opacity-60 whitespace-nowrap">{uploading?'⏳ Uploading…':'⬆️ Upload'}</button></div>
        {uploadResult&&(<div className={`rounded-lg p-3 text-sm ${uploadResult.error?'bg-red-50 text-red-800':'bg-green-50 text-green-800'}`}>{uploadResult.error?`❌ ${uploadResult.error}`:`✅ ${uploadResult.stats?.snapshots?.toLocaleString('en-IN')} rows · ${uploadResult.stats?.dates} dates · ${uploadResult.stats?.products} products — ${fmtMonth(uploadResult.month)}`}</div>)}
      </form></div>
    {loading?(<div className="flex items-center justify-center h-48"><div className="w-10 h-10 border-4 border-orange-500 border-t-transparent rounded-full animate-spin"></div></div>
    ):!hasData?(<div className="card p-10 text-center text-gray-500"><p className="text-3xl mb-3">📦</p><p className="font-semibold text-gray-700">No inventory data for {fmtMonth(viewMonth)}.</p><p className="text-sm mt-1">Upload aging CSV files above for this month to see holding cost analysis.</p></div>
    ):(<>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-4">{[{label:'Units Stored',value:s.total_units?.toLocaleString('en-IN'),icon:'📦',sub:`as of ${s.latest_date}`,color:'blue'},{label:'Units Sold This Month',value:s.total_units_sold?.toLocaleString('en-IN'),icon:'🛍️',sub:'forward orders',color:'green'},{label:'Total Aging Charges',value:fmt(s.total_charge),icon:'💸',sub:'incl. 18% GST',color:'red'},{label:'Capital Locked',value:fmt(s.capital_locked),icon:'🔒',sub:'stored units × COGS',color:'purple'}].map(c=>(<div key={c.label} className="card p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">{c.label}</p><p className="text-2xl font-bold text-gray-900">{c.value??'—'}</p>{c.sub&&<p className="text-xs text-gray-400 mt-1">{c.sub}</p>}</div><div className={`w-10 h-10 rounded-xl flex items-center justify-center text-xl ${c.color==='blue'?'bg-blue-50':c.color==='green'?'bg-green-50':c.color==='red'?'bg-red-50':'bg-purple-50'}`}>{c.icon}</div></div></div>))}</div>
      <div className="grid grid-cols-2 gap-4 mb-4"><div className="card p-5"><p className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">Projected Monthly Aging Cost</p><p className="text-2xl font-bold text-red-600">{fmt(s.proj_monthly)}</p><p className="text-xs text-gray-400 mt-1">if stock levels stay the same</p></div><div className="card p-5"><p className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">Products with Action Flags</p><p className="text-2xl font-bold text-amber-600">{s.products_with_flags}</p><p className="text-xs text-gray-400 mt-1">need attention (high aging / misplaced)</p></div></div>
      <div className="bg-gray-50 border border-gray-200 rounded-xl px-4 py-2 mb-4 text-xs text-gray-500 flex items-center gap-4"><span>Age slab costs (per unit/day):</span><span className="text-green-600 font-medium">0–30d = ₹1.00</span><span className="text-amber-600 font-medium">30–60d = ₹1.25</span><span className="text-red-600 font-medium">&gt;60d = ₹1.50</span><span className="ml-2 text-gray-400">Snapshot: {s.latest_date} ({s.all_dates?.length} dates)</span></div>
      <div className="card p-5"><h2 className="font-semibold text-gray-800 mb-4">Per-Product Holding Analysis — {fmtMonth(viewMonth)}</h2><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="font-medium text-gray-500 uppercase tracking-wider border-b border-gray-100"><th className="text-left pb-3 pr-3">Product</th><th className="text-right pb-3 px-2">Stored</th><th className="text-right pb-3 px-2">Sold</th><th className="text-right pb-3 px-2 text-green-600">0–30d</th><th className="text-right pb-3 px-2 text-amber-600">30–60d</th><th className="text-right pb-3 px-2 text-red-500">&gt;60d</th><th className="text-right pb-3 px-2">Darkstore</th><th className="text-right pb-3 px-2">Feeder WH</th><th className="text-right pb-3 px-2">Total Charge</th><th className="text-right pb-3 px-2">Proj/Month</th><th className="text-right pb-3 pl-2">Capital 🔒</th></tr></thead>
      <tbody className="divide-y divide-gray-50">{(data.products||[]).map(p=>(<tr key={p.item_id} className="hover:bg-gray-50"><td className="py-3 pr-3 max-w-[190px]"><p className="font-medium text-gray-800 truncate leading-tight">{p.item_name}</p>{p.flags.length>0&&(<div className="flex flex-wrap gap-1 mt-1">{p.flags.map((f,i)=>(<span key={i} className={`inline-block text-xs px-1.5 py-0.5 rounded font-medium ${f.type==='danger'?'bg-red-100 text-red-700':f.type==='warning'?'bg-amber-100 text-amber-700':'bg-blue-100 text-blue-700'}`}>{f.msg}</span>))}</div>)}</td><td className="py-3 px-2 text-right font-medium">{p.total_units}</td><td className="py-3 px-2 text-right text-green-700 font-medium">{p.units_sold>0?p.units_sold:<span className="text-gray-300">—</span>}</td><td className="py-3 px-2 text-right text-green-600">{p.slabs['0-30 Days']||0}</td><td className="py-3 px-2 text-right text-amber-600">{p.slabs['30-60 Days']||0}</td><td className={`py-3 px-2 text-right font-semibold ${p.slabs['>60 Days']>0?'text-red-600':'text-gray-300'}`}>{p.slabs['>60 Days']||0}</td><td className="py-3 px-2 text-right text-gray-600">{p.locations.darkstore}</td><td className={`py-3 px-2 text-right ${(p.locations.same_warehouse+p.locations.other_warehouse)>0?'text-amber-600':'text-gray-300'}`}>{p.locations.same_warehouse+p.locations.other_warehouse}</td><td className="py-3 px-2 text-right text-red-600 font-medium">{fmt(p.total_charge)}</td><td className={`py-3 px-2 text-right ${p.proj_monthly_charge>500?'text-red-600 font-semibold':'text-gray-600'}`}>{fmt(p.proj_monthly_charge)}</td><td className="py-3 pl-2 text-right text-gray-700">{p.capital_locked>0?fmt(p.capital_locked):<span className="text-amber-500">Set COGS</span>}</td></tr>))}</tbody>
      <tfoot className="border-t-2 border-gray-200 bg-gray-50 text-sm font-semibold"><tr><td className="py-3 pr-3 text-gray-800">Total</td><td className="py-3 px-2 text-right">{s.total_units}</td><td className="py-3 px-2 text-right text-green-700">{s.total_units_sold||0}</td><td colSpan={5}></td><td className="py-3 px-2 text-right text-red-600">{fmt(s.total_charge)}</td><td className="py-3 px-2 text-right text-red-600">{fmt(s.proj_monthly)}</td><td className="py-3 pl-2 text-right text-gray-700">{fmt(s.capital_locked)}</td></tr></tfoot></table></div></div>
    </>)}
  </main></div>);}
